# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Machine Learning/Fun stuff
email: qianyilong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love to learn and explore. In particular I love to learn about and implement AI
  and machine learning algorithms. Data manipulation also interests me.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: DanielRRich
github_username:  danielrich

# Build settings
markdown: kramdown
